// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};

/**
 * Body_login_api_v1_auth_login_post
 */
export type BodyLoginApiV1AuthLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * GenericResponse
 */
export type GenericResponse = {
    /**
     * Message
     *
     * A message describing the response
     */
    message: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MenuCreate
 */
export type MenuCreate = {
    /**
     * Name
     *
     * The name of the menu
     */
    name: string;
    /**
     * Description
     *
     * A description of the menu
     */
    description?: string | null;
    /**
     * Is Visible
     *
     * Whether the menu is visible
     */
    is_visible?: boolean | null;
};

/**
 * MenuItemCreate
 */
export type MenuItemCreate = {
    /**
     * Name
     *
     * The menu item name
     */
    name: string;
    /**
     * Description
     *
     * The menu item description
     */
    description?: string | null;
    /**
     * Pricing Type
     *
     * FIXED
     */
    pricing_type?: string | null;
    /**
     * Is Visible
     *
     * Whether the menu item is visible
     */
    is_visible?: boolean;
    /**
     * Prices
     *
     * List of prices for the menu item
     */
    prices?: Array<MenuItemPriceCreate>;
    /**
     * Prices Config
     *
     * Configuration for variable pricing, if applicable
     */
    prices_config?: {
        [key: string]: unknown;
    } | null;
};

/**
 * MenuItemPriceCreate
 */
export type MenuItemPriceCreate = {
    /**
     * Label
     *
     * The label for the menu item price
     */
    label: string;
    /**
     * Price
     *
     * The price for the menu item price
     */
    price: number;
};

/**
 * MenuItemPriceUpdate
 */
export type MenuItemPriceUpdate = {
    /**
     * Label
     */
    label: string;
    /**
     * Price
     */
    price: number;
    /**
     * Is Visible
     *
     * Whether the menu item price is visible
     */
    is_visible?: boolean | null;
};

/**
 * MenuItemResponse
 */
export type MenuItemResponse = {
    /**
     * Name
     *
     * The menu item name
     */
    name: string;
    /**
     * Description
     *
     * The menu item description
     */
    description?: string | null;
    /**
     * Pricing Type
     *
     * FIXED
     */
    pricing_type?: string | null;
    /**
     * Is Visible
     *
     * Whether the menu item is visible
     */
    is_visible?: boolean;
    /**
     * Prices
     *
     * List of prices for the menu item
     */
    prices?: Array<MenuItemPriceCreate>;
    /**
     * Prices Config
     *
     * Configuration for variable pricing, if applicable
     */
    prices_config?: {
        [key: string]: unknown;
    } | null;
    /**
     * Id
     */
    id: string;
};

/**
 * MenuItemUpdate
 */
export type MenuItemUpdate = {
    /**
     * Name
     *
     * The menu item name
     */
    name?: string | null;
    /**
     * Description
     *
     * The menu item description
     */
    description?: string | null;
    /**
     * Pricing Type
     *
     * FIXED
     */
    pricing_type?: string | null;
    /**
     * Is Visible
     *
     * Whether the menu item is visible
     */
    is_visible?: boolean | null;
    /**
     * Prices
     *
     * List of prices for the menu item
     */
    prices?: Array<MenuItemPriceUpdate> | null;
    /**
     * Prices Config
     *
     * Configuration for variable pricing, if applicable
     */
    prices_config?: {
        [key: string]: unknown;
    } | null;
};

/**
 * MenuResponse
 */
export type MenuResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Name
     *
     * The name of the menu
     */
    name: string;
    /**
     * Description
     *
     * A description of the menu
     */
    description?: string | null;
    /**
     * Is Visible
     *
     * Whether the menu is visible
     */
    is_visible?: boolean | null;
    /**
     * The QR code associated with this menu
     */
    qr?: QrResponse | null;
};

/**
 * MenuResponsePublic
 */
export type MenuResponsePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Name
     *
     * The name of the menu
     */
    name: string;
    /**
     * Description
     *
     * A description of the menu
     */
    description?: string | null;
    /**
     * Is Visible
     *
     * Whether the menu is visible
     */
    is_visible?: boolean | null;
    /**
     * The QR code associated with this menu
     */
    qr?: QrResponse | null;
    restaurant: RestaurantResponse;
    /**
     * Submenus
     *
     * List of submenus
     */
    submenus?: Array<SubMenuResponse>;
};

/**
 * MenuResponseWithRestaurant
 */
export type MenuResponseWithRestaurant = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Name
     *
     * The name of the menu
     */
    name: string;
    /**
     * Description
     *
     * A description of the menu
     */
    description?: string | null;
    /**
     * Is Visible
     *
     * Whether the menu is visible
     */
    is_visible?: boolean | null;
    /**
     * The QR code associated with this menu
     */
    qr?: QrResponse | null;
    restaurant: RestaurantResponse;
};

/**
 * MenuResponseWithSubmenus
 */
export type MenuResponseWithSubmenus = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Name
     *
     * The name of the menu
     */
    name: string;
    /**
     * Description
     *
     * A description of the menu
     */
    description?: string | null;
    /**
     * Is Visible
     *
     * Whether the menu is visible
     */
    is_visible?: boolean | null;
    /**
     * The QR code associated with this menu
     */
    qr?: QrResponse | null;
    /**
     * Submenus
     *
     * List of submenus
     */
    submenus?: Array<SubMenuResponse>;
};

/**
 * MenuUpdate
 */
export type MenuUpdate = {
    /**
     * Name
     *
     * The name of the menu
     */
    name?: string | null;
    /**
     * Description
     *
     * A description of the menu
     */
    description?: string | null;
    /**
     * Is Visible
     *
     * Whether the menu is visible
     */
    is_visible?: boolean | null;
};

/**
 * OTPResponse
 */
export type OtpResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Code
     */
    code: string;
    /**
     * Purpose
     */
    purpose: string;
    /**
     * Expires At
     */
    expires_at: string;
    /**
     * Is Used
     */
    is_used?: boolean | null;
};

/**
 * QRResponse
 */
export type QrResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Menu Id
     *
     * The ID of the menu this QR code belongs to
     */
    menu_id: string;
    /**
     * Restaurant Id
     *
     * The ID of the restaurant this QR code belongs to
     */
    restaurant_id: string;
    /**
     * Code
     */
    code: string;
    /**
     * Views
     */
    views: number;
};

/**
 * RestaurantCreate
 */
export type RestaurantCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Alias
     */
    alias: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * RestaurantResponse
 */
export type RestaurantResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Name
     */
    name: string;
    /**
     * Alias
     */
    alias: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Owner Id
     */
    owner_id?: string | null;
};

/**
 * RestaurantUpdate
 */
export type RestaurantUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ResturantResponseWithMenus
 */
export type ResturantResponseWithMenus = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Name
     */
    name: string;
    /**
     * Alias
     */
    alias: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Owner Id
     */
    owner_id?: string | null;
    /**
     * Menus
     */
    menus: Array<MenuResponse>;
};

/**
 * SubMenuCreate
 */
export type SubMenuCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Visible
     */
    is_visible?: boolean | null;
};

/**
 * SubMenuResponse
 */
export type SubMenuResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Visible
     */
    is_visible?: boolean | null;
    /**
     * Menu Id
     */
    menu_id: string;
    /**
     * Restaurant Id
     */
    restaurant_id: string;
    /**
     * Menu Items
     */
    menu_items?: Array<MenuItemResponse>;
};

/**
 * SubMenuUpdate
 */
export type SubMenuUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Visible
     */
    is_visible?: boolean | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Middle Name
     */
    middle_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Name
     */
    name: string;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Email
     */
    email: string | string;
    /**
     * Is Verified
     */
    is_verified?: boolean | null;
    /**
     * Status
     */
    status?: string | null;
};

/**
 * UserUnrestrictedResponse
 */
export type UserUnrestrictedResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Name
     */
    name: string;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Email
     */
    email: string | string;
    /**
     * Is Verified
     */
    is_verified?: boolean | null;
    /**
     * Status
     */
    status?: string | null;
    /**
     * Middle Name
     */
    middle_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Otps
     */
    otps?: Array<OtpResponse> | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VerifyEmailPayload
 */
export type VerifyEmailPayload = {
    /**
     * Otp
     */
    otp: string;
    /**
     * Email
     */
    email: string;
};

export type LoginApiV1AuthLoginPostData = {
    body: BodyLoginApiV1AuthLoginPost;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError = LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RegisterApiV1AuthRegisterPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterApiV1AuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterApiV1AuthRegisterPostError = RegisterApiV1AuthRegisterPostErrors[keyof RegisterApiV1AuthRegisterPostErrors];

export type RegisterApiV1AuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type VerifyUserApiV1AuthVerifyPostData = {
    body: VerifyEmailPayload;
    path?: never;
    query?: never;
    url: '/api/v1/auth/verify';
};

export type VerifyUserApiV1AuthVerifyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyUserApiV1AuthVerifyPostError = VerifyUserApiV1AuthVerifyPostErrors[keyof VerifyUserApiV1AuthVerifyPostErrors];

export type VerifyUserApiV1AuthVerifyPostResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type VerifyUserApiV1AuthVerifyPostResponse = VerifyUserApiV1AuthVerifyPostResponses[keyof VerifyUserApiV1AuthVerifyPostResponses];

export type GetMeApiV1AuthGetMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/get-me';
};

export type GetMeApiV1AuthGetMeGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAllUsersApiV1UsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type GetAllUsersApiV1UsersGetResponses = {
    /**
     * Response Get All Users Api V1 Users  Get
     *
     * Successful Response
     */
    200: Array<UserUnrestrictedResponse>;
};

export type GetAllUsersApiV1UsersGetResponse = GetAllUsersApiV1UsersGetResponses[keyof GetAllUsersApiV1UsersGetResponses];

export type DeleteUserApiV1UsersIdDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/users/{id}';
};

export type DeleteUserApiV1UsersIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserApiV1UsersIdDeleteError = DeleteUserApiV1UsersIdDeleteErrors[keyof DeleteUserApiV1UsersIdDeleteErrors];

export type DeleteUserApiV1UsersIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type DeleteUserApiV1UsersIdDeleteResponse = DeleteUserApiV1UsersIdDeleteResponses[keyof DeleteUserApiV1UsersIdDeleteResponses];

export type ReadRestaurantsApiV1RestaurantsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/restaurants';
};

export type ReadRestaurantsApiV1RestaurantsGetResponses = {
    /**
     * Response Read Restaurants Api V1 Restaurants Get
     *
     * Successful Response
     */
    200: Array<RestaurantResponse>;
};

export type ReadRestaurantsApiV1RestaurantsGetResponse = ReadRestaurantsApiV1RestaurantsGetResponses[keyof ReadRestaurantsApiV1RestaurantsGetResponses];

export type CreateRestaurantApiV1RestaurantsCreatePostData = {
    body: RestaurantCreate;
    path?: never;
    query?: never;
    url: '/api/v1/restaurants/create';
};

export type CreateRestaurantApiV1RestaurantsCreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRestaurantApiV1RestaurantsCreatePostError = CreateRestaurantApiV1RestaurantsCreatePostErrors[keyof CreateRestaurantApiV1RestaurantsCreatePostErrors];

export type CreateRestaurantApiV1RestaurantsCreatePostResponses = {
    /**
     * Successful Response
     */
    200: RestaurantResponse;
};

export type CreateRestaurantApiV1RestaurantsCreatePostResponse = CreateRestaurantApiV1RestaurantsCreatePostResponses[keyof CreateRestaurantApiV1RestaurantsCreatePostResponses];

export type ReadRestaurantByIdApiV1RestaurantsRestaurantIdGetData = {
    body?: never;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
    };
    query?: never;
    url: '/api/v1/restaurants/{restaurant_id}';
};

export type ReadRestaurantByIdApiV1RestaurantsRestaurantIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadRestaurantByIdApiV1RestaurantsRestaurantIdGetError = ReadRestaurantByIdApiV1RestaurantsRestaurantIdGetErrors[keyof ReadRestaurantByIdApiV1RestaurantsRestaurantIdGetErrors];

export type ReadRestaurantByIdApiV1RestaurantsRestaurantIdGetResponses = {
    /**
     * Successful Response
     */
    200: ResturantResponseWithMenus;
};

export type ReadRestaurantByIdApiV1RestaurantsRestaurantIdGetResponse = ReadRestaurantByIdApiV1RestaurantsRestaurantIdGetResponses[keyof ReadRestaurantByIdApiV1RestaurantsRestaurantIdGetResponses];

export type UpdateRestaurantApiV1RestaurantsRestaurantIdPutData = {
    body: RestaurantUpdate;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
    };
    query?: never;
    url: '/api/v1/restaurants/{restaurant_id}';
};

export type UpdateRestaurantApiV1RestaurantsRestaurantIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRestaurantApiV1RestaurantsRestaurantIdPutError = UpdateRestaurantApiV1RestaurantsRestaurantIdPutErrors[keyof UpdateRestaurantApiV1RestaurantsRestaurantIdPutErrors];

export type UpdateRestaurantApiV1RestaurantsRestaurantIdPutResponses = {
    /**
     * Successful Response
     */
    200: RestaurantResponse;
};

export type UpdateRestaurantApiV1RestaurantsRestaurantIdPutResponse = UpdateRestaurantApiV1RestaurantsRestaurantIdPutResponses[keyof UpdateRestaurantApiV1RestaurantsRestaurantIdPutResponses];

export type GetUsersOfRestaurantApiV1RestaurantsRestaurantIdUsersGetData = {
    body?: never;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
    };
    query?: never;
    url: '/api/v1/restaurants/{restaurant_id}/users';
};

export type GetUsersOfRestaurantApiV1RestaurantsRestaurantIdUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsersOfRestaurantApiV1RestaurantsRestaurantIdUsersGetError = GetUsersOfRestaurantApiV1RestaurantsRestaurantIdUsersGetErrors[keyof GetUsersOfRestaurantApiV1RestaurantsRestaurantIdUsersGetErrors];

export type GetUsersOfRestaurantApiV1RestaurantsRestaurantIdUsersGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPublicMenuApiV1MenusPublicCodeGetData = {
    body?: never;
    path: {
        /**
         * Code
         */
        code: string;
    };
    query?: never;
    url: '/api/v1/menus/public/{code}';
};

export type GetPublicMenuApiV1MenusPublicCodeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPublicMenuApiV1MenusPublicCodeGetError = GetPublicMenuApiV1MenusPublicCodeGetErrors[keyof GetPublicMenuApiV1MenusPublicCodeGetErrors];

export type GetPublicMenuApiV1MenusPublicCodeGetResponses = {
    /**
     * Successful Response
     */
    200: MenuResponsePublic;
};

export type GetPublicMenuApiV1MenusPublicCodeGetResponse = GetPublicMenuApiV1MenusPublicCodeGetResponses[keyof GetPublicMenuApiV1MenusPublicCodeGetResponses];

export type GetMenusApiV1MenusRestaurantIdGetData = {
    body?: never;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
    };
    query?: never;
    url: '/api/v1/menus/{restaurant_id}';
};

export type GetMenusApiV1MenusRestaurantIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMenusApiV1MenusRestaurantIdGetError = GetMenusApiV1MenusRestaurantIdGetErrors[keyof GetMenusApiV1MenusRestaurantIdGetErrors];

export type GetMenusApiV1MenusRestaurantIdGetResponses = {
    /**
     * Response Get Menus Api V1 Menus  Restaurant Id  Get
     *
     * Successful Response
     */
    200: Array<MenuResponseWithRestaurant>;
};

export type GetMenusApiV1MenusRestaurantIdGetResponse = GetMenusApiV1MenusRestaurantIdGetResponses[keyof GetMenusApiV1MenusRestaurantIdGetResponses];

export type CreateMenuApiV1MenusRestaurantIdPostData = {
    body: MenuCreate;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
    };
    query?: never;
    url: '/api/v1/menus/{restaurant_id}';
};

export type CreateMenuApiV1MenusRestaurantIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMenuApiV1MenusRestaurantIdPostError = CreateMenuApiV1MenusRestaurantIdPostErrors[keyof CreateMenuApiV1MenusRestaurantIdPostErrors];

export type CreateMenuApiV1MenusRestaurantIdPostResponses = {
    /**
     * Successful Response
     */
    200: GenericResponse;
};

export type CreateMenuApiV1MenusRestaurantIdPostResponse = CreateMenuApiV1MenusRestaurantIdPostResponses[keyof CreateMenuApiV1MenusRestaurantIdPostResponses];

export type GetMenuByIdApiV1MenusRestaurantIdMenuIdGetData = {
    body?: never;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
        /**
         * Menu Id
         */
        menu_id: string;
    };
    query?: never;
    url: '/api/v1/menus/{restaurant_id}/{menu_id}';
};

export type GetMenuByIdApiV1MenusRestaurantIdMenuIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMenuByIdApiV1MenusRestaurantIdMenuIdGetError = GetMenuByIdApiV1MenusRestaurantIdMenuIdGetErrors[keyof GetMenuByIdApiV1MenusRestaurantIdMenuIdGetErrors];

export type GetMenuByIdApiV1MenusRestaurantIdMenuIdGetResponses = {
    /**
     * Successful Response
     */
    200: MenuResponseWithSubmenus;
};

export type GetMenuByIdApiV1MenusRestaurantIdMenuIdGetResponse = GetMenuByIdApiV1MenusRestaurantIdMenuIdGetResponses[keyof GetMenuByIdApiV1MenusRestaurantIdMenuIdGetResponses];

export type UpdateMenuApiV1MenusRestaurantIdMenuIdPutData = {
    body: MenuUpdate;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
        /**
         * Menu Id
         */
        menu_id: string;
    };
    query?: never;
    url: '/api/v1/menus/{restaurant_id}/{menu_id}';
};

export type UpdateMenuApiV1MenusRestaurantIdMenuIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMenuApiV1MenusRestaurantIdMenuIdPutError = UpdateMenuApiV1MenusRestaurantIdMenuIdPutErrors[keyof UpdateMenuApiV1MenusRestaurantIdMenuIdPutErrors];

export type UpdateMenuApiV1MenusRestaurantIdMenuIdPutResponses = {
    /**
     * Successful Response
     */
    200: GenericResponse;
};

export type UpdateMenuApiV1MenusRestaurantIdMenuIdPutResponse = UpdateMenuApiV1MenusRestaurantIdMenuIdPutResponses[keyof UpdateMenuApiV1MenusRestaurantIdMenuIdPutResponses];

export type ListSubmenusApiV1SubmenusRestaurantIdMenuIdGetData = {
    body?: never;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
        /**
         * Menu Id
         */
        menu_id: string;
    };
    query?: never;
    url: '/api/v1/submenus/{restaurant_id}/{menu_id}';
};

export type ListSubmenusApiV1SubmenusRestaurantIdMenuIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSubmenusApiV1SubmenusRestaurantIdMenuIdGetError = ListSubmenusApiV1SubmenusRestaurantIdMenuIdGetErrors[keyof ListSubmenusApiV1SubmenusRestaurantIdMenuIdGetErrors];

export type ListSubmenusApiV1SubmenusRestaurantIdMenuIdGetResponses = {
    /**
     * Response List Submenus Api V1 Submenus  Restaurant Id   Menu Id  Get
     *
     * Successful Response
     */
    200: Array<SubMenuResponse>;
};

export type ListSubmenusApiV1SubmenusRestaurantIdMenuIdGetResponse = ListSubmenusApiV1SubmenusRestaurantIdMenuIdGetResponses[keyof ListSubmenusApiV1SubmenusRestaurantIdMenuIdGetResponses];

export type CreateSubmenuApiV1SubmenusRestaurantIdMenuIdPostData = {
    body: SubMenuCreate;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
        /**
         * Menu Id
         */
        menu_id: string;
    };
    query?: never;
    url: '/api/v1/submenus/{restaurant_id}/{menu_id}';
};

export type CreateSubmenuApiV1SubmenusRestaurantIdMenuIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSubmenuApiV1SubmenusRestaurantIdMenuIdPostError = CreateSubmenuApiV1SubmenusRestaurantIdMenuIdPostErrors[keyof CreateSubmenuApiV1SubmenusRestaurantIdMenuIdPostErrors];

export type CreateSubmenuApiV1SubmenusRestaurantIdMenuIdPostResponses = {
    /**
     * Successful Response
     */
    200: SubMenuResponse;
};

export type CreateSubmenuApiV1SubmenusRestaurantIdMenuIdPostResponse = CreateSubmenuApiV1SubmenusRestaurantIdMenuIdPostResponses[keyof CreateSubmenuApiV1SubmenusRestaurantIdMenuIdPostResponses];

export type UpdateSubmenuApiV1SubmenusRestaurantIdMenuIdSubmenuIdPatchData = {
    body: SubMenuUpdate;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
        /**
         * Menu Id
         */
        menu_id: string;
        /**
         * Submenu Id
         */
        submenu_id: string;
    };
    query?: never;
    url: '/api/v1/submenus/{restaurant_id}/{menu_id}/{submenu_id}';
};

export type UpdateSubmenuApiV1SubmenusRestaurantIdMenuIdSubmenuIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSubmenuApiV1SubmenusRestaurantIdMenuIdSubmenuIdPatchError = UpdateSubmenuApiV1SubmenusRestaurantIdMenuIdSubmenuIdPatchErrors[keyof UpdateSubmenuApiV1SubmenusRestaurantIdMenuIdSubmenuIdPatchErrors];

export type UpdateSubmenuApiV1SubmenusRestaurantIdMenuIdSubmenuIdPatchResponses = {
    /**
     * Successful Response
     */
    200: SubMenuResponse;
};

export type UpdateSubmenuApiV1SubmenusRestaurantIdMenuIdSubmenuIdPatchResponse = UpdateSubmenuApiV1SubmenusRestaurantIdMenuIdSubmenuIdPatchResponses[keyof UpdateSubmenuApiV1SubmenusRestaurantIdMenuIdSubmenuIdPatchResponses];

export type CreateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdPostData = {
    body: MenuItemCreate;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
        /**
         * Menu Id
         */
        menu_id: string;
        /**
         * Submenu Id
         */
        submenu_id: string;
    };
    query?: never;
    url: '/api/v1/menu-items/{restaurant_id}/{menu_id}/{submenu_id}';
};

export type CreateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdPostError = CreateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdPostErrors[keyof CreateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdPostErrors];

export type CreateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdPostResponses = {
    /**
     * Successful Response
     */
    200: GenericResponse;
};

export type CreateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdPostResponse = CreateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdPostResponses[keyof CreateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdPostResponses];

export type DeleteMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
        /**
         * Menu Id
         */
        menu_id: string;
        /**
         * Submenu Id
         */
        submenu_id: string;
        /**
         * Menu Item Id
         */
        menu_item_id: string;
    };
    query?: never;
    url: '/api/v1/menu-items/{restaurant_id}/{menu_id}/{submenu_id}/{menu_item_id}';
};

export type DeleteMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdDeleteError = DeleteMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdDeleteErrors[keyof DeleteMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdDeleteErrors];

export type DeleteMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: GenericResponse;
};

export type DeleteMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdDeleteResponse = DeleteMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdDeleteResponses[keyof DeleteMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdDeleteResponses];

export type UpdateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdPatchData = {
    body: MenuItemUpdate;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
        /**
         * Menu Id
         */
        menu_id: string;
        /**
         * Submenu Id
         */
        submenu_id: string;
        /**
         * Menu Item Id
         */
        menu_item_id: string;
    };
    query?: never;
    url: '/api/v1/menu-items/{restaurant_id}/{menu_id}/{submenu_id}/{menu_item_id}';
};

export type UpdateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdPatchError = UpdateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdPatchErrors[keyof UpdateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdPatchErrors];

export type UpdateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdPatchResponses = {
    /**
     * Successful Response
     */
    200: GenericResponse;
};

export type UpdateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdPatchResponse = UpdateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdPatchResponses[keyof UpdateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdPatchResponses];

export type GetQrCodesQGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/q/';
};

export type GetQrCodesQGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetQrImageQQrIdGetData = {
    body?: never;
    path: {
        /**
         * Qr Id
         */
        qr_id: string;
    };
    query?: never;
    url: '/q/{qr_id}';
};

export type GetQrImageQQrIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQrImageQQrIdGetError = GetQrImageQQrIdGetErrors[keyof GetQrImageQQrIdGetErrors];

export type GetQrImageQQrIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ResolveQrCodeQrQrCodeGetData = {
    body?: never;
    path: {
        /**
         * Qr Code
         */
        qr_code: string;
    };
    query?: never;
    url: '/q/r/{qr_code}';
};

export type ResolveQrCodeQrQrCodeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResolveQrCodeQrQrCodeGetError = ResolveQrCodeQrQrCodeGetErrors[keyof ResolveQrCodeQrQrCodeGetErrors];

export type ResolveQrCodeQrQrCodeGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
