// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};

/**
 * Body_login_api_v1_auth_login_post
 */
export type BodyLoginApiV1AuthLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ForgotPasswordPayload
 */
export type ForgotPasswordPayload = {
    /**
     * Email
     */
    email: string;
};

/**
 * GenericResponse
 */
export type GenericResponse = {
    /**
     * Message
     *
     * A message describing the response
     */
    message: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
    data: LoginResponseData;
};

/**
 * LoginResponseData
 */
export type LoginResponseData = {
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Middle Name
     */
    middle_name?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Is Verified
     */
    is_verified: boolean;
    /**
     * Status
     */
    status: string;
    /**
     * App Role
     */
    app_role: string;
};

/**
 * MenuConfigurationSchema
 */
export type MenuConfigurationSchema = {
    /**
     * Template Id
     *
     * The template id of the menu configuration
     */
    template_id: string;
};

/**
 * MenuCreate
 */
export type MenuCreate = {
    /**
     * Name
     *
     * The name of the menu
     */
    name: string;
    /**
     * Description
     *
     * A description of the menu
     */
    description?: string | null;
    /**
     * Is Visible
     *
     * Whether the menu is visible
     */
    is_visible?: boolean | null;
    /**
     * The configuration of the menu
     */
    menu_configuration?: MenuConfigurationSchema | null;
};

/**
 * MenuItemCreate
 */
export type MenuItemCreate = {
    /**
     * Name
     *
     * The menu item name
     */
    name: string;
    /**
     * Description
     *
     * The menu item description
     */
    description?: string | null;
    /**
     * Pricing Type
     *
     * FIXED
     */
    pricing_type?: string | null;
    /**
     * Is Visible
     *
     * Whether the menu item is visible
     */
    is_visible?: boolean;
    /**
     * The status of the menu item
     */
    status?: MenuItemStatus | null;
    /**
     * Prices
     *
     * List of prices for the menu item
     */
    prices?: Array<MenuItemPriceCreate>;
    /**
     * Prices Config
     *
     * Configuration for variable pricing, if applicable
     */
    prices_config?: {
        [key: string]: unknown;
    } | null;
};

/**
 * MenuItemPriceCreate
 */
export type MenuItemPriceCreate = {
    /**
     * Label
     *
     * The label for the menu item price
     */
    label: string;
    /**
     * Price
     *
     * The price for the menu item price
     */
    price: number;
};

/**
 * MenuItemPriceUpdate
 */
export type MenuItemPriceUpdate = {
    /**
     * Label
     */
    label: string;
    /**
     * Price
     */
    price: number;
    /**
     * Is Visible
     *
     * Whether the menu item price is visible
     */
    is_visible?: boolean | null;
};

/**
 * MenuItemResponse
 */
export type MenuItemResponse = {
    /**
     * Name
     *
     * The menu item name
     */
    name: string;
    /**
     * Description
     *
     * The menu item description
     */
    description?: string | null;
    /**
     * Pricing Type
     *
     * FIXED
     */
    pricing_type?: string | null;
    /**
     * Is Visible
     *
     * Whether the menu item is visible
     */
    is_visible?: boolean;
    /**
     * The status of the menu item
     */
    status?: MenuItemStatus | null;
    /**
     * Prices
     *
     * List of prices for the menu item
     */
    prices?: Array<MenuItemPriceCreate>;
    /**
     * Prices Config
     *
     * Configuration for variable pricing, if applicable
     */
    prices_config?: {
        [key: string]: unknown;
    } | null;
    /**
     * Id
     */
    id: string;
    /**
     * Order Index
     */
    order_index: number;
};

/**
 * MenuItemStatus
 */
export type MenuItemStatus = 'AVAILABLE' | 'UNAVAILABLE';

/**
 * MenuItemUpdate
 */
export type MenuItemUpdate = {
    /**
     * Name
     *
     * The menu item name
     */
    name?: string | null;
    /**
     * Description
     *
     * The menu item description
     */
    description?: string | null;
    /**
     * The status of the menu item
     */
    status?: MenuItemStatus | null;
    /**
     * Pricing Type
     *
     * FIXED
     */
    pricing_type?: string | null;
    /**
     * Is Visible
     *
     * Whether the menu item is visible
     */
    is_visible?: boolean | null;
    /**
     * Prices
     *
     * List of prices for the menu item
     */
    prices?: Array<MenuItemPriceUpdate> | null;
    /**
     * Prices Config
     *
     * Configuration for variable pricing, if applicable
     */
    prices_config?: {
        [key: string]: unknown;
    } | null;
};

/**
 * MenuPaginatedResponse
 */
export type MenuPaginatedResponse = {
    /**
     * Data
     */
    data: Array<MenuResponse>;
    pagination: PaginationMeta;
};

/**
 * MenuResponse
 */
export type MenuResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Name
     *
     * The name of the menu
     */
    name: string;
    /**
     * Description
     *
     * A description of the menu
     */
    description?: string | null;
    /**
     * Is Visible
     *
     * Whether the menu is visible
     */
    is_visible?: boolean | null;
    /**
     * The configuration of the menu
     */
    menu_configuration?: MenuConfigurationSchema | null;
    /**
     * The QR code associated with this menu
     */
    qr?: QrResponse | null;
};

/**
 * MenuResponsePublic
 */
export type MenuResponsePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Name
     *
     * The name of the menu
     */
    name: string;
    /**
     * Description
     *
     * A description of the menu
     */
    description?: string | null;
    /**
     * Is Visible
     *
     * Whether the menu is visible
     */
    is_visible?: boolean | null;
    /**
     * The configuration of the menu
     */
    menu_configuration?: MenuConfigurationSchema | null;
    /**
     * The QR code associated with this menu
     */
    qr?: QrResponse | null;
    restaurant: RestaurantResponse;
    /**
     * Submenus
     *
     * List of submenus
     */
    submenus?: Array<SubMenuResponse>;
};

/**
 * MenuResponseWithSubmenus
 */
export type MenuResponseWithSubmenus = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Name
     *
     * The name of the menu
     */
    name: string;
    /**
     * Description
     *
     * A description of the menu
     */
    description?: string | null;
    /**
     * Is Visible
     *
     * Whether the menu is visible
     */
    is_visible?: boolean | null;
    /**
     * The configuration of the menu
     */
    menu_configuration?: MenuConfigurationSchema | null;
    /**
     * The QR code associated with this menu
     */
    qr?: QrResponse | null;
    /**
     * Submenus
     *
     * List of submenus
     */
    submenus?: Array<SubMenuResponse>;
};

/**
 * MenuUpdate
 */
export type MenuUpdate = {
    /**
     * Name
     *
     * The name of the menu
     */
    name?: string | null;
    /**
     * Description
     *
     * A description of the menu
     */
    description?: string | null;
    /**
     * Is Visible
     *
     * Whether the menu is visible
     */
    is_visible?: boolean | null;
    /**
     * The configuration of the menu
     */
    menu_configuration?: MenuConfigurationSchema | null;
};

/**
 * OrderIndex
 */
export type OrderIndex = {
    /**
     * Item Id
     */
    item_id: string;
    /**
     * Order Index
     *
     * The new order index for the item
     */
    order_index: number;
};

/**
 * PaginationMeta
 */
export type PaginationMeta = {
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Total
     */
    total: number;
    /**
     * Total Pages
     */
    total_pages: number;
};

/**
 * PermissionResponse
 */
export type PermissionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * QRResponse
 */
export type QrResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Menu Id
     *
     * The ID of the menu this QR code belongs to
     */
    menu_id: string;
    /**
     * Restaurant Id
     *
     * The ID of the restaurant this QR code belongs to
     */
    restaurant_id: string;
    /**
     * Code
     */
    code: string;
    /**
     * Views
     */
    views: number;
};

/**
 * ResendVerificationPayload
 */
export type ResendVerificationPayload = {
    /**
     * Email
     */
    email: string;
};

/**
 * ResetPasswordPayload
 */
export type ResetPasswordPayload = {
    /**
     * Email
     */
    email: string;
    /**
     * Otp
     */
    otp: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * RestaurantCreate
 */
export type RestaurantCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Alias
     */
    alias: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * RestaurantResponse
 */
export type RestaurantResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Name
     */
    name: string;
    /**
     * Alias
     */
    alias: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Owner Id
     */
    owner_id?: string | null;
};

/**
 * RestaurantUpdate
 */
export type RestaurantUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ResturantResponseWithMenus
 */
export type ResturantResponseWithMenus = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Name
     */
    name: string;
    /**
     * Alias
     */
    alias: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Owner Id
     */
    owner_id?: string | null;
    /**
     * Menus
     */
    menus: Array<MenuResponse>;
};

/**
 * RolesResponse
 */
export type RolesResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Restaurant Id
     */
    restaurant_id: string;
    /**
     * Permissions
     */
    permissions: Array<PermissionResponse>;
};

/**
 * SubMenuCreate
 */
export type SubMenuCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Visible
     */
    is_visible?: boolean | null;
};

/**
 * SubMenuResponse
 */
export type SubMenuResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Visible
     */
    is_visible?: boolean | null;
    /**
     * Menu Id
     */
    menu_id: string;
    /**
     * Restaurant Id
     */
    restaurant_id: string;
    /**
     * Order Index
     */
    order_index: number;
    /**
     * Menu Items
     */
    menu_items?: Array<MenuItemResponse>;
};

/**
 * SubMenuUpdate
 */
export type SubMenuUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Visible
     */
    is_visible?: boolean | null;
};

/**
 * TemplateSchema
 */
export type TemplateSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Version
     */
    version: string;
    /**
     * Category
     */
    category: string;
    /**
     * Preview Image
     */
    preview_image?: string | null;
};

/**
 * UpdateOrderIndex
 */
export type UpdateOrderIndex = {
    /**
     * New Order
     *
     * A list of submenu IDs in the new order
     */
    new_order: Array<OrderIndex>;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Middle Name
     */
    middle_name?: string | null;
    /**
     * App Role
     */
    app_role?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPaginatedResponse
 */
export type UserPaginatedResponse = {
    /**
     * Data
     */
    data: Array<UserResponse>;
    pagination: PaginationMeta;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Name
     */
    name: string;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Middle Name
     */
    middle_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Email
     */
    email: string | string;
    /**
     * Is Verified
     */
    is_verified?: boolean | null;
    app_role: UserRole;
    /**
     * Status
     */
    status?: string | null;
};

/**
 * UserRole
 */
export type UserRole = 'SUPER_ADMIN' | 'ADMIN' | 'USER';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VerifyEmailPayload
 */
export type VerifyEmailPayload = {
    /**
     * Otp
     */
    otp: string;
    /**
     * Email
     */
    email: string;
};

export type GetPermissionsApiV1RolesAndPermissionsPermissionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/roles-and-permissions/permissions';
};

export type GetPermissionsApiV1RolesAndPermissionsPermissionsGetResponses = {
    /**
     * Response Get Permissions Api V1 Roles And Permissions Permissions Get
     *
     * Successful Response
     */
    200: Array<PermissionResponse>;
};

export type GetPermissionsApiV1RolesAndPermissionsPermissionsGetResponse = GetPermissionsApiV1RolesAndPermissionsPermissionsGetResponses[keyof GetPermissionsApiV1RolesAndPermissionsPermissionsGetResponses];

export type GetRolesApiV1RolesAndPermissionsRolesRestaurantIdGetData = {
    body?: never;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
    };
    query?: never;
    url: '/api/v1/roles-and-permissions/roles/{restaurant_id}';
};

export type GetRolesApiV1RolesAndPermissionsRolesRestaurantIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRolesApiV1RolesAndPermissionsRolesRestaurantIdGetError = GetRolesApiV1RolesAndPermissionsRolesRestaurantIdGetErrors[keyof GetRolesApiV1RolesAndPermissionsRolesRestaurantIdGetErrors];

export type GetRolesApiV1RolesAndPermissionsRolesRestaurantIdGetResponses = {
    /**
     * Response Get Roles Api V1 Roles And Permissions Roles  Restaurant Id  Get
     *
     * Successful Response
     */
    200: Array<RolesResponse>;
};

export type GetRolesApiV1RolesAndPermissionsRolesRestaurantIdGetResponse = GetRolesApiV1RolesAndPermissionsRolesRestaurantIdGetResponses[keyof GetRolesApiV1RolesAndPermissionsRolesRestaurantIdGetResponses];

export type LoginApiV1AuthLoginPostData = {
    body: BodyLoginApiV1AuthLoginPost;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError = LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: LoginResponse;
};

export type LoginApiV1AuthLoginPostResponse = LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type RegisterApiV1AuthRegisterPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterApiV1AuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterApiV1AuthRegisterPostError = RegisterApiV1AuthRegisterPostErrors[keyof RegisterApiV1AuthRegisterPostErrors];

export type RegisterApiV1AuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type VerifyUserApiV1AuthVerifyPostData = {
    body: VerifyEmailPayload;
    path?: never;
    query?: never;
    url: '/api/v1/auth/verify';
};

export type VerifyUserApiV1AuthVerifyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyUserApiV1AuthVerifyPostError = VerifyUserApiV1AuthVerifyPostErrors[keyof VerifyUserApiV1AuthVerifyPostErrors];

export type VerifyUserApiV1AuthVerifyPostResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type VerifyUserApiV1AuthVerifyPostResponse = VerifyUserApiV1AuthVerifyPostResponses[keyof VerifyUserApiV1AuthVerifyPostResponses];

export type ResendVerificationApiV1AuthResendVerificationPostData = {
    body: ResendVerificationPayload;
    path?: never;
    query?: never;
    url: '/api/v1/auth/resend-verification';
};

export type ResendVerificationApiV1AuthResendVerificationPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResendVerificationApiV1AuthResendVerificationPostError = ResendVerificationApiV1AuthResendVerificationPostErrors[keyof ResendVerificationApiV1AuthResendVerificationPostErrors];

export type ResendVerificationApiV1AuthResendVerificationPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ForgotPasswordApiV1AuthForgotPasswordPostData = {
    body: ForgotPasswordPayload;
    path?: never;
    query?: never;
    url: '/api/v1/auth/forgot-password';
};

export type ForgotPasswordApiV1AuthForgotPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ForgotPasswordApiV1AuthForgotPasswordPostError = ForgotPasswordApiV1AuthForgotPasswordPostErrors[keyof ForgotPasswordApiV1AuthForgotPasswordPostErrors];

export type ForgotPasswordApiV1AuthForgotPasswordPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ResetPasswordApiV1AuthResetPasswordPostData = {
    body: ResetPasswordPayload;
    path?: never;
    query?: never;
    url: '/api/v1/auth/reset-password';
};

export type ResetPasswordApiV1AuthResetPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetPasswordApiV1AuthResetPasswordPostError = ResetPasswordApiV1AuthResetPasswordPostErrors[keyof ResetPasswordApiV1AuthResetPasswordPostErrors];

export type ResetPasswordApiV1AuthResetPasswordPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMeApiV1AuthGetMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/get-me';
};

export type GetMeApiV1AuthGetMeGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMyDetailsApiV1AuthGetMyDetailsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/get-my-details';
};

export type GetMyDetailsApiV1AuthGetMyDetailsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAllUsersApiV1UsersRestaurantIdGetData = {
    body?: never;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/users/{restaurant_id}';
};

export type GetAllUsersApiV1UsersRestaurantIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllUsersApiV1UsersRestaurantIdGetError = GetAllUsersApiV1UsersRestaurantIdGetErrors[keyof GetAllUsersApiV1UsersRestaurantIdGetErrors];

export type GetAllUsersApiV1UsersRestaurantIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserPaginatedResponse;
};

export type GetAllUsersApiV1UsersRestaurantIdGetResponse = GetAllUsersApiV1UsersRestaurantIdGetResponses[keyof GetAllUsersApiV1UsersRestaurantIdGetResponses];

export type ReadRestaurantsApiV1RestaurantsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/restaurants';
};

export type ReadRestaurantsApiV1RestaurantsGetResponses = {
    /**
     * Response Read Restaurants Api V1 Restaurants Get
     *
     * Successful Response
     */
    200: Array<RestaurantResponse>;
};

export type ReadRestaurantsApiV1RestaurantsGetResponse = ReadRestaurantsApiV1RestaurantsGetResponses[keyof ReadRestaurantsApiV1RestaurantsGetResponses];

export type CreateRestaurantApiV1RestaurantsCreatePostData = {
    body: RestaurantCreate;
    path?: never;
    query?: never;
    url: '/api/v1/restaurants/create';
};

export type CreateRestaurantApiV1RestaurantsCreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRestaurantApiV1RestaurantsCreatePostError = CreateRestaurantApiV1RestaurantsCreatePostErrors[keyof CreateRestaurantApiV1RestaurantsCreatePostErrors];

export type CreateRestaurantApiV1RestaurantsCreatePostResponses = {
    /**
     * Successful Response
     */
    200: RestaurantResponse;
};

export type CreateRestaurantApiV1RestaurantsCreatePostResponse = CreateRestaurantApiV1RestaurantsCreatePostResponses[keyof CreateRestaurantApiV1RestaurantsCreatePostResponses];

export type ReadRestaurantByIdApiV1RestaurantsRestaurantIdGetData = {
    body?: never;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
    };
    query?: never;
    url: '/api/v1/restaurants/{restaurant_id}';
};

export type ReadRestaurantByIdApiV1RestaurantsRestaurantIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadRestaurantByIdApiV1RestaurantsRestaurantIdGetError = ReadRestaurantByIdApiV1RestaurantsRestaurantIdGetErrors[keyof ReadRestaurantByIdApiV1RestaurantsRestaurantIdGetErrors];

export type ReadRestaurantByIdApiV1RestaurantsRestaurantIdGetResponses = {
    /**
     * Successful Response
     */
    200: ResturantResponseWithMenus;
};

export type ReadRestaurantByIdApiV1RestaurantsRestaurantIdGetResponse = ReadRestaurantByIdApiV1RestaurantsRestaurantIdGetResponses[keyof ReadRestaurantByIdApiV1RestaurantsRestaurantIdGetResponses];

export type UpdateRestaurantApiV1RestaurantsRestaurantIdPutData = {
    body: RestaurantUpdate;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
    };
    query?: never;
    url: '/api/v1/restaurants/{restaurant_id}';
};

export type UpdateRestaurantApiV1RestaurantsRestaurantIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRestaurantApiV1RestaurantsRestaurantIdPutError = UpdateRestaurantApiV1RestaurantsRestaurantIdPutErrors[keyof UpdateRestaurantApiV1RestaurantsRestaurantIdPutErrors];

export type UpdateRestaurantApiV1RestaurantsRestaurantIdPutResponses = {
    /**
     * Successful Response
     */
    200: RestaurantResponse;
};

export type UpdateRestaurantApiV1RestaurantsRestaurantIdPutResponse = UpdateRestaurantApiV1RestaurantsRestaurantIdPutResponses[keyof UpdateRestaurantApiV1RestaurantsRestaurantIdPutResponses];

export type GetUsersOfRestaurantApiV1RestaurantsRestaurantIdUsersGetData = {
    body?: never;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
    };
    query?: never;
    url: '/api/v1/restaurants/{restaurant_id}/users';
};

export type GetUsersOfRestaurantApiV1RestaurantsRestaurantIdUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsersOfRestaurantApiV1RestaurantsRestaurantIdUsersGetError = GetUsersOfRestaurantApiV1RestaurantsRestaurantIdUsersGetErrors[keyof GetUsersOfRestaurantApiV1RestaurantsRestaurantIdUsersGetErrors];

export type GetUsersOfRestaurantApiV1RestaurantsRestaurantIdUsersGetResponses = {
    /**
     * Response Get Users Of Restaurant Api V1 Restaurants  Restaurant Id  Users Get
     *
     * Successful Response
     */
    200: Array<UserResponse> | null;
};

export type GetUsersOfRestaurantApiV1RestaurantsRestaurantIdUsersGetResponse = GetUsersOfRestaurantApiV1RestaurantsRestaurantIdUsersGetResponses[keyof GetUsersOfRestaurantApiV1RestaurantsRestaurantIdUsersGetResponses];

export type GetPublicMenuApiV1MenusPublicCodeGetData = {
    body?: never;
    path: {
        /**
         * Code
         */
        code: string;
    };
    query?: never;
    url: '/api/v1/menus/public/{code}';
};

export type GetPublicMenuApiV1MenusPublicCodeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPublicMenuApiV1MenusPublicCodeGetError = GetPublicMenuApiV1MenusPublicCodeGetErrors[keyof GetPublicMenuApiV1MenusPublicCodeGetErrors];

export type GetPublicMenuApiV1MenusPublicCodeGetResponses = {
    /**
     * Successful Response
     */
    200: MenuResponsePublic;
};

export type GetPublicMenuApiV1MenusPublicCodeGetResponse = GetPublicMenuApiV1MenusPublicCodeGetResponses[keyof GetPublicMenuApiV1MenusPublicCodeGetResponses];

export type GetMenusApiV1MenusRestaurantIdGetData = {
    body?: never;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/menus/{restaurant_id}';
};

export type GetMenusApiV1MenusRestaurantIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMenusApiV1MenusRestaurantIdGetError = GetMenusApiV1MenusRestaurantIdGetErrors[keyof GetMenusApiV1MenusRestaurantIdGetErrors];

export type GetMenusApiV1MenusRestaurantIdGetResponses = {
    /**
     * Successful Response
     */
    200: MenuPaginatedResponse;
};

export type GetMenusApiV1MenusRestaurantIdGetResponse = GetMenusApiV1MenusRestaurantIdGetResponses[keyof GetMenusApiV1MenusRestaurantIdGetResponses];

export type CreateMenuApiV1MenusRestaurantIdPostData = {
    body: MenuCreate;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
    };
    query?: never;
    url: '/api/v1/menus/{restaurant_id}';
};

export type CreateMenuApiV1MenusRestaurantIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMenuApiV1MenusRestaurantIdPostError = CreateMenuApiV1MenusRestaurantIdPostErrors[keyof CreateMenuApiV1MenusRestaurantIdPostErrors];

export type CreateMenuApiV1MenusRestaurantIdPostResponses = {
    /**
     * Successful Response
     */
    200: MenuResponseWithSubmenus;
};

export type CreateMenuApiV1MenusRestaurantIdPostResponse = CreateMenuApiV1MenusRestaurantIdPostResponses[keyof CreateMenuApiV1MenusRestaurantIdPostResponses];

export type GetMenuByIdApiV1MenusRestaurantIdMenuIdGetData = {
    body?: never;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
        /**
         * Menu Id
         */
        menu_id: string;
    };
    query?: never;
    url: '/api/v1/menus/{restaurant_id}/{menu_id}';
};

export type GetMenuByIdApiV1MenusRestaurantIdMenuIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMenuByIdApiV1MenusRestaurantIdMenuIdGetError = GetMenuByIdApiV1MenusRestaurantIdMenuIdGetErrors[keyof GetMenuByIdApiV1MenusRestaurantIdMenuIdGetErrors];

export type GetMenuByIdApiV1MenusRestaurantIdMenuIdGetResponses = {
    /**
     * Successful Response
     */
    200: MenuResponseWithSubmenus;
};

export type GetMenuByIdApiV1MenusRestaurantIdMenuIdGetResponse = GetMenuByIdApiV1MenusRestaurantIdMenuIdGetResponses[keyof GetMenuByIdApiV1MenusRestaurantIdMenuIdGetResponses];

export type UpdateMenuApiV1MenusRestaurantIdMenuIdPutData = {
    body: MenuUpdate;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
        /**
         * Menu Id
         */
        menu_id: string;
    };
    query?: never;
    url: '/api/v1/menus/{restaurant_id}/{menu_id}';
};

export type UpdateMenuApiV1MenusRestaurantIdMenuIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMenuApiV1MenusRestaurantIdMenuIdPutError = UpdateMenuApiV1MenusRestaurantIdMenuIdPutErrors[keyof UpdateMenuApiV1MenusRestaurantIdMenuIdPutErrors];

export type UpdateMenuApiV1MenusRestaurantIdMenuIdPutResponses = {
    /**
     * Successful Response
     */
    200: GenericResponse;
};

export type UpdateMenuApiV1MenusRestaurantIdMenuIdPutResponse = UpdateMenuApiV1MenusRestaurantIdMenuIdPutResponses[keyof UpdateMenuApiV1MenusRestaurantIdMenuIdPutResponses];

export type ListSubmenusApiV1SubmenusRestaurantIdMenuIdGetData = {
    body?: never;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
        /**
         * Menu Id
         */
        menu_id: string;
    };
    query?: never;
    url: '/api/v1/submenus/{restaurant_id}/{menu_id}';
};

export type ListSubmenusApiV1SubmenusRestaurantIdMenuIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSubmenusApiV1SubmenusRestaurantIdMenuIdGetError = ListSubmenusApiV1SubmenusRestaurantIdMenuIdGetErrors[keyof ListSubmenusApiV1SubmenusRestaurantIdMenuIdGetErrors];

export type ListSubmenusApiV1SubmenusRestaurantIdMenuIdGetResponses = {
    /**
     * Response List Submenus Api V1 Submenus  Restaurant Id   Menu Id  Get
     *
     * Successful Response
     */
    200: Array<SubMenuResponse>;
};

export type ListSubmenusApiV1SubmenusRestaurantIdMenuIdGetResponse = ListSubmenusApiV1SubmenusRestaurantIdMenuIdGetResponses[keyof ListSubmenusApiV1SubmenusRestaurantIdMenuIdGetResponses];

export type CreateSubmenuApiV1SubmenusRestaurantIdMenuIdPostData = {
    body: SubMenuCreate;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
        /**
         * Menu Id
         */
        menu_id: string;
    };
    query?: never;
    url: '/api/v1/submenus/{restaurant_id}/{menu_id}';
};

export type CreateSubmenuApiV1SubmenusRestaurantIdMenuIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSubmenuApiV1SubmenusRestaurantIdMenuIdPostError = CreateSubmenuApiV1SubmenusRestaurantIdMenuIdPostErrors[keyof CreateSubmenuApiV1SubmenusRestaurantIdMenuIdPostErrors];

export type CreateSubmenuApiV1SubmenusRestaurantIdMenuIdPostResponses = {
    /**
     * Successful Response
     */
    200: SubMenuResponse;
};

export type CreateSubmenuApiV1SubmenusRestaurantIdMenuIdPostResponse = CreateSubmenuApiV1SubmenusRestaurantIdMenuIdPostResponses[keyof CreateSubmenuApiV1SubmenusRestaurantIdMenuIdPostResponses];

export type UpdateSubmenuOrderApiV1SubmenusRestaurantIdMenuIdOrderPatchData = {
    body: UpdateOrderIndex;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
        /**
         * Menu Id
         */
        menu_id: string;
    };
    query?: never;
    url: '/api/v1/submenus/{restaurant_id}/{menu_id}/order';
};

export type UpdateSubmenuOrderApiV1SubmenusRestaurantIdMenuIdOrderPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSubmenuOrderApiV1SubmenusRestaurantIdMenuIdOrderPatchError = UpdateSubmenuOrderApiV1SubmenusRestaurantIdMenuIdOrderPatchErrors[keyof UpdateSubmenuOrderApiV1SubmenusRestaurantIdMenuIdOrderPatchErrors];

export type UpdateSubmenuOrderApiV1SubmenusRestaurantIdMenuIdOrderPatchResponses = {
    /**
     * Response Update Submenu Order Api V1 Submenus  Restaurant Id   Menu Id  Order Patch
     *
     * Successful Response
     */
    200: Array<SubMenuResponse>;
};

export type UpdateSubmenuOrderApiV1SubmenusRestaurantIdMenuIdOrderPatchResponse = UpdateSubmenuOrderApiV1SubmenusRestaurantIdMenuIdOrderPatchResponses[keyof UpdateSubmenuOrderApiV1SubmenusRestaurantIdMenuIdOrderPatchResponses];

export type UpdateSubmenuApiV1SubmenusRestaurantIdMenuIdSubmenuIdPatchData = {
    body: SubMenuUpdate;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
        /**
         * Menu Id
         */
        menu_id: string;
        /**
         * Submenu Id
         */
        submenu_id: string;
    };
    query?: never;
    url: '/api/v1/submenus/{restaurant_id}/{menu_id}/{submenu_id}';
};

export type UpdateSubmenuApiV1SubmenusRestaurantIdMenuIdSubmenuIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSubmenuApiV1SubmenusRestaurantIdMenuIdSubmenuIdPatchError = UpdateSubmenuApiV1SubmenusRestaurantIdMenuIdSubmenuIdPatchErrors[keyof UpdateSubmenuApiV1SubmenusRestaurantIdMenuIdSubmenuIdPatchErrors];

export type UpdateSubmenuApiV1SubmenusRestaurantIdMenuIdSubmenuIdPatchResponses = {
    /**
     * Successful Response
     */
    200: SubMenuResponse;
};

export type UpdateSubmenuApiV1SubmenusRestaurantIdMenuIdSubmenuIdPatchResponse = UpdateSubmenuApiV1SubmenusRestaurantIdMenuIdSubmenuIdPatchResponses[keyof UpdateSubmenuApiV1SubmenusRestaurantIdMenuIdSubmenuIdPatchResponses];

export type CreateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdPostData = {
    body: MenuItemCreate;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
        /**
         * Menu Id
         */
        menu_id: string;
        /**
         * Submenu Id
         */
        submenu_id: string;
    };
    query?: never;
    url: '/api/v1/menu-items/{restaurant_id}/{menu_id}/{submenu_id}';
};

export type CreateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdPostError = CreateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdPostErrors[keyof CreateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdPostErrors];

export type CreateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdPostResponses = {
    /**
     * Successful Response
     */
    200: GenericResponse;
};

export type CreateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdPostResponse = CreateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdPostResponses[keyof CreateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdPostResponses];

export type UpdateMenuItemsOrderApiV1MenuItemsRestaurantIdMenuIdSubmenuIdOrderPatchData = {
    body: UpdateOrderIndex;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
        /**
         * Menu Id
         */
        menu_id: string;
        /**
         * Submenu Id
         */
        submenu_id: string;
    };
    query?: never;
    url: '/api/v1/menu-items/{restaurant_id}/{menu_id}/{submenu_id}/order';
};

export type UpdateMenuItemsOrderApiV1MenuItemsRestaurantIdMenuIdSubmenuIdOrderPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMenuItemsOrderApiV1MenuItemsRestaurantIdMenuIdSubmenuIdOrderPatchError = UpdateMenuItemsOrderApiV1MenuItemsRestaurantIdMenuIdSubmenuIdOrderPatchErrors[keyof UpdateMenuItemsOrderApiV1MenuItemsRestaurantIdMenuIdSubmenuIdOrderPatchErrors];

export type UpdateMenuItemsOrderApiV1MenuItemsRestaurantIdMenuIdSubmenuIdOrderPatchResponses = {
    /**
     * Successful Response
     */
    200: GenericResponse;
};

export type UpdateMenuItemsOrderApiV1MenuItemsRestaurantIdMenuIdSubmenuIdOrderPatchResponse = UpdateMenuItemsOrderApiV1MenuItemsRestaurantIdMenuIdSubmenuIdOrderPatchResponses[keyof UpdateMenuItemsOrderApiV1MenuItemsRestaurantIdMenuIdSubmenuIdOrderPatchResponses];

export type DeleteMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
        /**
         * Menu Id
         */
        menu_id: string;
        /**
         * Submenu Id
         */
        submenu_id: string;
        /**
         * Menu Item Id
         */
        menu_item_id: string;
    };
    query?: never;
    url: '/api/v1/menu-items/{restaurant_id}/{menu_id}/{submenu_id}/{menu_item_id}';
};

export type DeleteMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdDeleteError = DeleteMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdDeleteErrors[keyof DeleteMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdDeleteErrors];

export type DeleteMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: GenericResponse;
};

export type DeleteMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdDeleteResponse = DeleteMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdDeleteResponses[keyof DeleteMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdDeleteResponses];

export type UpdateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdPatchData = {
    body: MenuItemUpdate;
    path: {
        /**
         * Restaurant Id
         */
        restaurant_id: string;
        /**
         * Menu Id
         */
        menu_id: string;
        /**
         * Submenu Id
         */
        submenu_id: string;
        /**
         * Menu Item Id
         */
        menu_item_id: string;
    };
    query?: never;
    url: '/api/v1/menu-items/{restaurant_id}/{menu_id}/{submenu_id}/{menu_item_id}';
};

export type UpdateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdPatchError = UpdateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdPatchErrors[keyof UpdateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdPatchErrors];

export type UpdateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdPatchResponses = {
    /**
     * Successful Response
     */
    200: GenericResponse;
};

export type UpdateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdPatchResponse = UpdateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdPatchResponses[keyof UpdateMenuItemApiV1MenuItemsRestaurantIdMenuIdSubmenuIdMenuItemIdPatchResponses];

export type GetAllTemplatesApiV1MenuTemplatesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/menu-templates';
};

export type GetAllTemplatesApiV1MenuTemplatesGetResponses = {
    /**
     * Response Get All Templates Api V1 Menu Templates Get
     *
     * Successful Response
     */
    200: Array<TemplateSchema>;
};

export type GetAllTemplatesApiV1MenuTemplatesGetResponse = GetAllTemplatesApiV1MenuTemplatesGetResponses[keyof GetAllTemplatesApiV1MenuTemplatesGetResponses];

export type GetTemplateByIdApiV1MenuTemplatesTemplateIdGetData = {
    body?: never;
    path: {
        /**
         * Template Id
         */
        template_id: string;
    };
    query?: never;
    url: '/api/v1/menu-templates/{template_id}';
};

export type GetTemplateByIdApiV1MenuTemplatesTemplateIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTemplateByIdApiV1MenuTemplatesTemplateIdGetError = GetTemplateByIdApiV1MenuTemplatesTemplateIdGetErrors[keyof GetTemplateByIdApiV1MenuTemplatesTemplateIdGetErrors];

export type GetTemplateByIdApiV1MenuTemplatesTemplateIdGetResponses = {
    /**
     * Successful Response
     */
    200: TemplateSchema;
};

export type GetTemplateByIdApiV1MenuTemplatesTemplateIdGetResponse = GetTemplateByIdApiV1MenuTemplatesTemplateIdGetResponses[keyof GetTemplateByIdApiV1MenuTemplatesTemplateIdGetResponses];

export type GetQrCodesQGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/q/';
};

export type GetQrCodesQGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetQrImageQQrIdGetData = {
    body?: never;
    path: {
        /**
         * Qr Id
         */
        qr_id: string;
    };
    query?: never;
    url: '/q/{qr_id}';
};

export type GetQrImageQQrIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQrImageQQrIdGetError = GetQrImageQQrIdGetErrors[keyof GetQrImageQQrIdGetErrors];

export type GetQrImageQQrIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ResolveQrCodeQrQrCodeGetData = {
    body?: never;
    path: {
        /**
         * Qr Code
         */
        qr_code: string;
    };
    query?: never;
    url: '/q/r/{qr_code}';
};

export type ResolveQrCodeQrQrCodeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResolveQrCodeQrQrCodeGetError = ResolveQrCodeQrQrCodeGetErrors[keyof ResolveQrCodeQrQrCodeGetErrors];

export type ResolveQrCodeQrQrCodeGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
